### ISSUE TITLE
How heatmap works?

### ISSUE THREAD

**Issue by Fundoprajakta** [gmplot/gmplot#109]
Hello,

I could not find a proper documentation for gmplot heatmap. 
Is there a way, I can draw weighted heatmap?
For example: earthquake data with long, lat and intensity of earthquake.

**Comment by sandrotosi** [comment]
@Fundoprajakta heatmaps show a concentration density, the more dense of points an area is the more colored is (the _heat_ is higher). f.e. in http://sandrotosi.me/ingress/nyc/nyc_portals_heatmap.html the more read it is, the denser the area is (of points i'm interested in as part of this map), as you can zoom, you can see these areas tend to dilute.

to address your problem, since there's not a density involved, you may want to try and simulate it by using markers of different colors: red for higher h.q. intensity, blue for lower lever and so on

**Comment by sandrotosi** [comment]
closing, feel free to reopen if you need more info (would be ideal to point to places where we can improve our doc)
