### ISSUE TITLE
Add differnt markers

### ISSUE THREAD

**Issue by AbbasHommadi** [gmplot/gmplot#47]
Hi there,
I like to visualize a route with gmplot. This route has single origin, single destination, and multiple way points. I'd like to add different marker for all origin, destination, and way points. I tried this but it doesn't work. It keep just the last change and make all markers identical to this last change. Any help will be appreciated.
  
    def plot_markers(self, gm_plotter, lats, lngs, titles):
        """
        This method plot marker to GoogleMapPlotter. Where lats[0] and lngs[0] is the origin, lats[-1] and lngs[-1] 
        is the desination, and all the inbetween are waypoints. 
        :param gm_plotter: GoogleMapPlotter object
        :param lats: (list of floats) a list of latitudes
        :param lngs: (list of floats) a list of longitudes.
        :return: (GoogleMapPlotter) google map plotter object that could be for further processing.
        """
        gm_plotter.coloricon = 'http://www.googlemapsmarkers.com/v1/'+titles[0]+'/%s/FFFFFF/0080ff/' 
        gm_plotter.marker(lats[0], lngs[0], title=titles[0])
        gm_plotter.coloricon = 'http://www.googlemapsmarkers.com/v1/' + titles[-1] + '/%s/FFFFFF/0080ff/'
        gm_plotter.marker(lats[-1], lngs[-1], title=titles[-1])
        for lat, lng, title in zip(lats[1:-1], lngs[1:-1], titles[1:-1]):
            gm_plotter.coloricon = 'http://www.googlemapsmarkers.com/v1/' + title + '/%s/FFFFFF/0080ff/'
            gm_plotter.marker(lat, lng, title=title)
        return gm_plotter

**Comment by vgm64** [comment]
Sorry for not responding. Is this still a problem you're having?

**Comment by frslm** [comment]
`coloricon` is only used by gmplot when you call `gm_plotter.draw()` or `gm_plotter.get()`, so it doesn't matter how many times you change it; it'll always used the icon you last set it to (only its color will change, but the label will be the same for all markers).

Instead of modifying `coloricon` multiple times, just set it once, without a label...
```python
gm_plotter.coloricon = 'http://www.googlemapsmarkers.com/v1/%s/'
# (you gotta find a way to set the border color without setting a label though)
```
...then pass in a label for each `marker()` call, for example:
```python
gm_plotter.marker(lats[0], lngs[0], title=titles[0], label=titles[0])
```

This won't let you customize the color of your labels though; they'll always be black. If you'd like more customization for labels, feel free to create an Issue to request it, or better yet, create a new Pull request that adds it.
