### ISSUE TITLE
Title of scatter's markers

### ISSUE THREAD

**Issue by yyykkkyyy** [gmplot/gmplot#83]
Hi,
We can use markers as scatter points.
Can I add title str to those markers like normal marker ?
Or can I display markers without word balloons ?

**Comment by frslm** [comment]
> Can I add title str to those markers like normal marker ?

@yyykkkyyy and @msalvador96, this was just merged into master in #152 - you can now specify the title for specific markers:
```python
map.scatter(lats, lngs, title=['First', 'Second', 'Third', 'Fourth'])
```

> Or can I display markers without word balloons ?

I'm assuming you're talking about that "no implementation" title that used to show up when hovering over markers. That's been fixed so that nothing appears by default when hovering over a marker.
